### ISSUE TITLE
Transductive Method?

### ISSUE THREAD

**Issue by 00why00** [shule-deng/RFDNet#1]
In your code: 
https://github.com/shule-deng/RFDNet/blob/main/utils.py#L306
You use all the query data to do the attention, so whether this is a transductive method?

**Comment by shule-deng** [comment]
Our method is not transductive method. In our method, each query generates a corresponding feature displacement. The code in https://github.com/shule-deng/RFDNet/blob/main/utils.py#L306 is used to generate the feature displacement. As for the task-adaptive attention you mentioned, it is generated in https://github.com/shule-deng/RFDNet/blob/main/utils.py#L259. I'm sorry that maybe the name of variables in the code has caused you confusion, I will modify it later. Wish my replay can help you.
