### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by z1358** [shule-deng/RFDNet#2]
The links of Mini-ImageNet and Tiered-ImageNet are not working. Could you please update them?

**Comment by shule-deng** [comment]
Thank you for your comments. I have updated the relevant link. Now, you can download the Mini-ImageNet on https://drive.google.com/file/d/1X7jZFU9S8YOeLC1YjELPM8AFYC6f-AYt/view?usp=sharing and the Tiered-ImageNet  on https://drive.google.com/file/d/1yq8HZZyZ7atvINg0ix5S0uHm3wz9sU5Q/view?usp=sharing. Hope you found this useful
